import os
from dotenv import load_dotenv

# Load environment variables
load_dotenv()

# ADK Imports
from google.adk.agents import LlmAgent
from google.adk.tools import google_search

# -------------------------------------------------------------------------
# Define the Root Agent
# -------------------------------------------------------------------------
root_agent = LlmAgent(
    model="gemini-2.5-pro",
    name="adk_cloudrun_risk_analyst",
    description=(
        "An enterprise-grade Risk Analysis Agent deployed on Cloud Run."
    ),
    instruction="""You are an expert Risk Analyst Agent. 
You have access to Google Search.

When a user asks a question about property & casualty insurance, operational risks, or general business intelligence:
1. Utilize the Google Search tool to gather the latest facts and industry reports.
2. Formulate a structured analysis outlining:
   - Key Operational Risks
   - Market Impacts
   - Strategic Recommendations
3. Cite your search sources clearly.

MANDATORY DISCLAIMER:
You must append these exact disclaimers at the very bottom of every response:
- 'This insight was generated by an AI agent deployed on Google Cloud Run.'
- 'Outputs should be validated by Risk Management Subject Matter Experts (SMEs) before making strategic business decisions.'""",
    tools=[google_search]
)

if __name__ == "__main__":
    print("Agent 'adk_cloudrun_risk_analyst' loaded successfully.")
